### ISSUE TITLE
Not being to upload Custom Variables as a part of CM offline conversion data

### ISSUE THREAD

**Issue by Sandhya-1988** [google/megalista#57] opened 2022-02-07 21:38 UTC
Hi There,

We are running Megalista implementation for a client for quite a long time. It's been working wonderfully so far.
However, in one of the scenarios, where we use the CM offline conversion upload functionality, it uploads all the data except Custom Variables. Below are the steps that we have performed and confirmed at our end. 

1. All these custom variables are available and enabled on the floodlight level.
2. We also used regular API calls to push these same variables into the CM platform and that worked fine. So the problem is not with the data or setup on the CM part.

We value your time and effort. However, it would be of huge help if it would be possible to look at this from Megalista's end.
Any help or guidance would be highly appreciated, as we are not sure how to proceed beyond this point.

Additionally, if any input is needed from our end, we would be happy to contribute.

Thanks & Regards,
Sandhya

**Comment by caiotomazelli** [comment] 2022-02-17 19:41
Hi Sandhya.

First of all, sorry for the delay in getting back to you.

Can you confirm when this instance of Megalista was deployed on your client environment?

It would be really helpful to know the Megalista "version" they're running so that we can pinpoint the issue.

For your reference, we've merged the [commit that implemented custom variables](https://github.com/google/megalista/pull/41) in Megalista on Aug 16, 2021, so if you've deployed Megalista for this client earlier, high chances that they're just using an old version.

If not, let us know and we can try to debug it together.

Cheers,
Caio

**Comment by Sandhya-1988** [comment] 2022-02-18 18:43
> Hi Sandhya.
> 
> First of all, sorry for the delay in getting back to you.
> 
> Can you confirm when this instance of Megalista was deployed on your client environment?
> 
> It would be really helpful to know the Megalista "version" they're running so that we can pinpoint the issue.
> 
> For your reference, we've merged the [commit that implemented custom variables](https://github.com/google/megalista/pull/41) in Megalista on Aug 16, 2021, so if you've deployed Megalista for this client earlier, high chances that they're just using an old version.
> 
> If not, let us know and we can try to debug it together.
> 
> Cheers, Caio

Hi Caio,

Thank you so much for your response. I really appreciate it and no worries about the delay part.

Regarding the "Megalista version", I did a redeploy with the latest version around a month and a half back, as the previous version deployed was "Megalist".
Also, I went through pull request #41, it seems the code running in the client's env is updated with the same.

Kindly let me know how to move forward with this. Also, happy to provide more details if needed.

Thanks,
Sandhya

**Comment by caiotomazelli** [comment] 2022-02-18 21:41
Thanks for confirming Sandhya!

This is kind of surprising because we do have tests verifying that the customVariables are built into the final CM API body for the CM connector (see [here](https://github.com/google/megalista/blob/e00937d73ac1404312c280241cffe00e89e93892/megalista_dataflow/uploaders/campaign_manager/campaign_manager_conversion_uploader_test.py#L133) for your reference).

Can you provide an anonymized/mock sample of the data you're trying to upload so that I can try to reproduce the issue on my side? Maybe there's some specific structure that you're trying to use that we have not predict in our tests.

**Comment by Sandhya-1988** [comment] 2022-02-22 21:25
> Thanks for confirming Sandhya!
> 
> This is kind of surprising because we do have tests verifying that the customVariables are built into the final CM API body for the CM connector (see [here](https://github.com/google/megalista/blob/e00937d73ac1404312c280241cffe00e89e93892/megalista_dataflow/uploaders/campaign_manager/campaign_manager_conversion_uploader_test.py#L133) for your reference).
> 
> Can you provide an anonymized/mock sample of the data you're trying to upload so that I can try to reproduce the issue on my side? Maybe there's some specific structure that you're trying to use that we have not predict in our tests.

Thanks again for your quick response Caio! Really appreciate it.

Please find here a screenshot of the sample data for your reference.
![Screen Shot 2022-02-22 at 12 45 26 PM](https://user-images.githubusercontent.com/50858989/155221668-b6902de9-8536-4ef4-b337-ed2837cc9c5a.png)

In the above screenshot, Variables U1, U3, and U7 stand for ConfCode, OAB_ID, and Device ID, respectively. I hope this helps. 
Kindly let me know f I can help with anything else.

**Comment by Sandhya-1988** [comment] 2022-03-01 16:29
Hi @caiotomazelli, 

I hope the sample data that I shared earlier has been of help. But was just curious to know if there are any updates related to the same. Additionally, happy to help with any further data/information or support.

Thanks,
Sandhya

**Comment by caiotomazelli** [comment] 2022-03-04 22:13
Hi @Sandhya-1988 sorry for the delay getting back to you.

Looks like it's going to be an easy fix: your custom variable columns are using snake_case as opposed to camelCase, which is what we expect, as you can see below:

![image](https://user-images.githubusercontent.com/9386901/156848592-7e526bc8-874c-4f62-8147-7c0ccd67b876.png)

Also, check out our [Example BQ Data for Testing](https://github.com/google/megalista/wiki/Campaign-Manager-Offline-Conversions#example-bq-data-for-testing) to see how data should be structured in BQ for customVariables (it must be a single Array column).

I'll close the issue for now but feel free to reopen if you need anything else.

Cheers,
Caio

**Closed by caiotomazelli** 2022-03-04 22:13 UTC
